#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\DefaultController::index

signup:
  path: /signup
  controller: App\Controller\DefaultController::signup

